### ISSUE TITLE
SQLiteLog: (1) no such table: 

### ISSUE THREAD

**Issue by nvhaiwork** [supaldubey/storm#1]
Hello, I'm facing an issue when use your lib, can you help me to solve it?
Step 1:

@Table(name = "TestTable")
public class Test {

	@PrimaryKey
	@Column(name = "shit", type = FieldType.INTEGER)
	private int id;
}

Step 2:
@in.cubestack.android.lib.storm.annotation.Database(name = "owna_app", tables = {Test.class}, version = 2)
class Database {
}

Step 3:
private static StormService mService;

	public DataDAO(Context ctx) {

		//if (mService == null) {

			mService = new BaseService(ctx, Database.class);
		//}
	}

	public boolean isChildEmpty() {

		List<Test> child = null;
		try {

			child = mService.findAll(Test.class);
		} catch (Exception e) {

			LogUtil.e("isChildEmpty", e.getMessage());
		}

		return child == null || child.size() == 0;
	}

**Comment by supaldubey** [comment]
Hey @nvhaiwork 

Seems there is a version mismatch issue here. 

Your database is assuming the version to be 2, since your @Table annotation does not have a version it defaults to 1. Thus service assumes the table to be of an older version and does not creates it. 

Your options:
1) Add version information to @Table annotation with version 2
2) Remove version info from @Database or set it as 1.

Let me know if this helps with your issue.

**Comment by nvhaiwork** [comment]
Thanks for your help but I still facing this problem.

Step1 now:

@Table(name = "TestTable", version = 2)
public class Test {

	@PrimaryKey
	@Column(name = "shit", type = FieldType.INTEGER)
	private int id;
}

**Comment by supaldubey** [comment]
Ok, since you have already run your application SQLIte database version 2 has been already registered. 

Thus, the database update did not work, can you try bumping up the version attributes in both annotations to 3. That should resolve this issue.

**Comment by nvhaiwork** [comment]
wwowww, it works now, Thanks you :P

**Comment by supaldubey** [comment]
Perfect! Glad to be of help. Hope you enjoy using Storm and all the best for your project. 

Open another issue if you need any help
